services:
  - type: web
    name: fan-based-item-tracking-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd server && python app.py"
    envVars:
      - key: DATABASE_URL
        value: 'sqlite:///app.db' 