services:
  - type: web
    name: fan-based-item-tracking-app
    env: python
     buildCommand: 
      - "pip install -r requirements.txt"
      - "flask db upgrade"
    startCommand: "gunicorn --chdir server app:app"
    startCommand: poetry run python app.py
    envVars:
      - key: DATABASE_URL
        value: 'sqlite:///app.db' 

   
