services:
  - type: web
    name: fan-based-item-tracking-app
    env: python
     buildCommand: 
      - "pip install -r requirements.txt && npm install --prefix client && npm run build --prefix client"
      - "flask db upgrade"
    startCommand: "gunicorn --chdir server app:app"
    envVars:
      - key: DATABASE_URL
        value: 'sqlite:///app.db' 

   
