services:
  - type: web
    name: fan-based-item-tracking-app
    env: python
    buildCommand: poetry install
    startCommand: poetry run python app.py
    envVars:
      - key: DATABASE_URL
        value: 'sqlite:///app.db' 
